services:
  web:
    build: .
    image: test:${DOCKER_IMAGE_TAG:-latest}
    container_name: test
    volumes:
      - /tmp/jenkins_workspace:/code # Jenkins 디렉터리 대신 임시 디렉터리 사용
    ports:
      - "6004:6004"
    environment:
`